config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'inbox', to: 'pages#inbox'
  get 'profile', to: 'pages#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def inbox
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bubbletap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>BUBBLETAP</h1>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1>
    <%= link_to "Larson One", profile_path %>
  </h1>
</div>
<div>
  <p>Mehdi_Cherche_Pas</p>
  <p>Jess_filou</p>
  <p>Anis_Dz_de_Grignard</p>
  <p>Nounours_Palpal</p>
</div>
<div>
<p>Chaise De Burreau</p>

</div>

app/views/pages/inbox.html.erb
<h1>Inbox</h1>
  <h1>
    <%= link_to "Retour", inbox_path %>
  </h1>
</div>

app/views/pages/profile.html.erb
<div>
  <h1>
    Mon Profile
  </h1>
</div>
<div>
  <h1>
    <%= link_to "Retour", inbox_path %>
  </h1>
</div>